### ISSUE TITLE
Negative values

### ISSUE THREAD

**Issue by dmamontov** [blynkkk/blynk-server#909] opened 2018-02-09 19:32 UTC
With negative accelerometer values or joystick, an error is issued that the server is obsolete, update it. I tried both on the local and on the general.

**Comment by doom369** [comment] 2018-02-09 19:36
Not sure what do you mean. Where do you put negative values?

**Comment by dmamontov** [comment] 2018-02-09 19:42
Version 2.18.1

https://ibb.co/fTMobH

**Comment by doom369** [comment] 2018-02-09 20:06
This is Android, right?

**Comment by dmamontov** [comment] 2018-02-09 20:07
All right!

**Comment by dmamontov** [comment] 2018-02-09 20:10
At the accelerometer, the values vary from -10 to 10. For example, if we turn to have a positive value, then everything is in order. If the negative one writes an error. The same is true for the joystick if you set the minimum value to negative.

**Comment by doom369** [comment] 2018-02-11 09:55
@dmamontov we couldn't reproduce this issue. Some additional details? Minimal steps to reproduce?

**Comment by dmamontov** [comment] 2018-02-11 13:27
Arduino Nano + BT HC-06
```c
#define BLYNK_USE_DIRECT_CONNECT

#include <SoftwareSerial.h>
SoftwareSerial DebugSerial(2, 3); // RX, TX

#define BLYNK_PRINT DebugSerial
#include <BlynkSimpleSerialBLE.h>

char auth[] = "a9e795c7fe6b4806b861e13cb43d4de1";
//char auth[] = "1c3cd0b35bf242538029db8b860a7511";

WidgetTerminal terminal(V0);

//Accselerometr
BLYNK_WRITE(V1) {
  int x = param[0].asInt(); 
  //acceleration force applied to axis y
  int y = param[1].asInt();
  //acceleration force applied to axis y

  //terminal.print(F("x: "));
  //terminal.println(x);
  //terminal.print(F("y: "));
  //terminal.println(y-);
  //terminal.flush();
}

void setup() {
  DebugSerial.begin(9600);
  DebugSerial.println("Waiting for connections...");
  
  Serial.begin(9600);
  Blynk.begin(Serial, auth);
}

void loop() {
  Blynk.run();
}
```

in the settings of the joystick set pin v1. merge method. the minimum value of -255 is maximal 255 on both axes.

Android 8.1, Google Nexus 5x.

**Comment by doom369** [comment] 2018-02-11 15:09
@dmamontov thanks! will be fixed with next Android update.

**Closed by doom369** 2018-02-11 15:09 UTC
