### ISSUE TITLE
Not updating after pause

### ISSUE THREAD

**Issue by scargill** [blynkkk/blynk-server#105] opened 2016-01-29 09:52 UTC
Even after today's update... if you use the square stop button top right of the APP screen - make a change to the state of a button externally then use the triangle top right of screen to continue - the APP is unaware of the changes made externally.

If stopped COMPLETELY, a change is made externally and the APP is started - it DOES know about changes so the server appears to be working properly, but when using the square to pause the APP then on continuing using the triangle top right of screen - the APP is NOT aware of changes made in the meantime.

Tested on latest APP update and latest (today) SERVER after rebooting the server.

**Comment by doom369** [comment] 2016-01-29 09:55
Thank you. Reproduced.

**Comment by scargill** [comment] 2016-01-31 10:01
Hi

 

Just wondering when we can expect an App update to fix this one? Would be great…

 

Pete.

**Comment by doom369** [comment] 2016-01-31 10:14
The issue is application bug and not server. But app developers are busy at the moment with other tasks. So I think issue will be fixed in 2 weeks. Not earlier.

**Comment by doom369** [comment] 2016-02-03 20:27
Fixed for server. Created appropriate tickets for apps.

**Closed by doom369** 2016-02-03 20:27 UTC
Labels: bug

**Comment by scargill** [comment] 2016-02-10 10:08
Can we expect a fix for this issue this week?? Recall this is the issue that if you pause the APP, it does not catch up with changes on the webserver when you resume…

**Comment by doom369** [comment] 2016-02-10 10:52
Yes, for Android.

**Comment by scargill** [comment] 2016-02-14 08:53
No sign of expected fix to Android Blink to update App status after pause, 
identified 2 weeks ago??

**Comment by doom369** [comment] 2016-02-14 18:12
@scargill issue not critical and we are limited in resources so it may be not fast. Please be patient.

**Comment by scargill** [comment] 2016-02-14 19:05
Will be patient  thanks – it is critical for me as I can’t use Blynk without it…. Looking forward to seeing this fix.

**Comment by doom369** [comment] 2016-02-14 19:27
I'll do my best to make release tomorrow, but no promises. Thanks.

**Comment by scargill** [comment] 2016-02-14 20:16
You would be my hero….. when the update is out I will blog it.

**Comment by doom369** [comment] 2016-02-15 22:30
@scargill app was just published. Please let me know if it doesn't work as expected.

**Comment by scargill** [comment] 2016-02-15 23:30
I checked just before reading this – I will indeed let you know. Thank you.

**Comment by scargill** [comment] 2016-02-15 23:50
When logging into the local server, the app says

 

“Command is bad formed, check syntax and passed params”.

 

???

 

Never seen that before.

 

Pete.

**Comment by doom369** [comment] 2016-02-15 23:51
You need to use 0.12.6 server version.

**Comment by scargill** [comment] 2016-02-16 00:10
Correct. Thank you for that.

 

To answer your question….yes, on preliminary testing – just with a button and a slider.. and testing both pause and app swapping… this is the behaviour I would expect. The app now at least in those simple tests – is aware of background changes when the app is not visible.

 

Excellent – now to start some proper testing. A great start to my week. It would appear that this is now worth putting some work into. 

Thanks.

 

Pete.

**Comment by doom369** [comment] 2016-02-16 00:11
Cool. Glad you liked it. Happy Blynking!
